Update build_native.yml

diff --git a/.github/workflows/build_native.yml b/.github/workflows/build_native.yml
--- a/.github/workflows/build_native.yml
+++ b/.github/workflows/build_native.yml
@@ -43,6 +43,7 @@ jobs:
         mkdir -p ${{ env.PREFIX }}
         mkdir -p ${{ env.CACHE_PATH }}
         sudo apt update && sudo apt install -y build-essential flex bison texinfo libgmp-dev libmpfr-dev libmpc-dev wine
+        (sudo dpkg --add-architecture i386 && sudo apt-get install wine32:i386)||echo "Failed to install wine32!"
         # wine is not necessary, only for testing
     - name: Download artifact
       uses: actions/download-artifact@v4
@@ -89,7 +90,7 @@ jobs:
         $CXX -print-prog-name=cc1
         cat << EOF | tee test.c
         #include <stdio.h>
-        int main(void) { printf("Hello, World!"); }
+        int main(void) { printf("Hello, World!\n"); }
         EOF
 
         cat << EOF | tee tthread.cpp
@@ -128,7 +129,8 @@ jobs:
         mkdir build && cd build
         ../configure --host=$CROSS_PREFIX --target=$TARGET --prefix=$PREFIX --with-sysroot=$SYSROOT \
             --disable-shared --enable-static --disable-multilib --disable-nls --enable-lto --disable-gdb
-        make -j$(nproc)
+        echo "[debug] starting to build binutils"
+        make V=1 -j$(nproc)
         make install
     - name: Configure and build MinGW-w64 headers
       run: |
